language: node_js
node_js:
- 8.9.4
dist: trusty
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_f8a05f79b5b6_key -iv $encrypted_f8a05f79b5b6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: "<shell script/command that runs on deploy>"
  on:
    branch: master
