/**
 * Write and export action types.
 * ex: export const ADD_TODO = 'ADD_TODO';
*/
/* Environment ActionTypes */
export const ENVIRONMENT_RESIZE = 'ENVIRONMENT_RESIZE';

/* Modal ActionTypes */
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_CLOSE = 'MODAL_CLOSE';

/* Toast ActionTypes */
export const TOAST_ADD = 'TOAST_ADD';
export const TOAST_DELETE = 'TOAST_DELETE';

/* User ActionTypes */
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_VALIDATE_REQUEST = 'USER_VALIDATE_REQUEST';
export const USER_VALIDATE_SUCCESS = 'USER_VALIDATE_SUCCESS';
export const USER_VALIDATE_FAILURE = 'USER_VALIDATE_FAILURE';
export const USER_VALIDATE_INITIALIZE = 'USER_VALIDATE_INITIALIZE';

export const USER_VERIFY_REQUEST = 'USER_VERIFY_REQUEST';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_VERIFY_FAILURE = 'USER_VERIFY_FAILURE';

/* Log ActionTypes */
export const LOG_POST_REQUEST = 'LOG_POST_REQUEST';
export const LOG_POST_SUCCESS = 'LOG_POST_SUCCESS';
export const LOG_POST_FAILURE = 'LOG_POST_FAILURE';

export const LOG_LIST_REQUEST = 'LOG_LIST_REQUEST';
export const LOG_LIST_SUCCESS = 'LOG_LIST_SUCCESS';
export const LOG_LIST_FAILURE = 'LOG_LIST_FAILURE';

export const LOG_GET_REQUEST = 'LOG_GET_REQUEST';
export const LOG_GET_SUCCESS = 'LOG_GET_SUCCESS';
export const LOG_GET_FAILURE = 'LOG_GET_FAILURE';

/* Search ActionTypes */
export const SEARCH_TAG_REQUEST = 'SEARCH_TAG_REQUEST';
export const SEARCH_TAG_SUCCESS = 'SEARCH_TAG_SUCCESS';
export const SEARCH_TAG_FAILURE = 'SEARCH_TAG_FAILURE';
